language:
   - python

python:
   - 2.7

install:
   - pip install -U pip
   - pip install pytest pytest-pep8 pytest-cov python-coveralls
   - pip install matplotlib

before_script: # configure a headless display to test plot generation
   - "export DISPLAY=:99.0"
   - "sh -e /etc/init.d/xvfb start"
   - sleep 3 

script:
   #- make PY=py.test PYFLAGS='--cov=srcpy' test
   #- make PY=py.test PYFLAGS='--cov=srcpy' examples example=rand-init
   #- make PY=py.test PYFLAGS='--cov=srcpy' examples example=cannon
   - py.test test/test.py --cov=srcpy
   
after_success:
   - coveralls

notifications:
  email: false
