language:
   - python

python:
   - 2.6
   - 2.7

install:
   - pip install -U pip
   - pip install pytest pytest-pep8

script:
   - make test
   - make examples example=cannon

notifications:
  email: false